### PR TITLE
Move from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by javer**
It seems that Github Actions are disabled for this repository, you can see successful build here: https://github.com/javer/php-amqp/actions/runs/640067053

### CODE REVIEW

**Comment by mlocati** [comment]
@javer as I wrote in https://github.com/php-amqp/php-amqp/issues/389#issuecomment-795194138 and https://github.com/php-amqp/php-amqp/issues/386#issuecomment-795194782 I'm already working on github actions: why didn't you write that you too was going to work on that?

**Comment by mlocati** [comment]
@javer sure I will, but a collaborative project involves collaboration. If one says he'll do something, and you want to do it yourself instead, you should day that. Why? Because that would have saved me a few hours I already spent on this...

**Comment by Yozhef** [comment]
@mlocati In my opinion, nothing problematic happened - the faster it is implemented the better a stable version will be released.

**Comment by mlocati** [comment]
@Yozhef sure, it's really great to have such lighting fast pull requests. I was just telling @javer that if he added a note about this pull request I wouldn't have wasted a few hours

**Comment by lstrojny** [comment]
Thank you very much!

Can we do one change to the matrix: let's build each PHP version against all three library versions and keep having a single -m version for each PHP version against different library versions each. I would hope we would still be below 15 min build time.

**Comment by javer** [comment]
@lstrojny  If I understood you correctly, I made the following matrix:

| PHP \ librabbitmq | master | v0.8.0 | v0.7.1 |
| - | - | - | - |
| 8.0 | m | + | + |
| 7.4 | + | m | + |
| 7.3 | + | + | m |
| 7.2 | m | + | + |
| 7.1 | + | m | + |
| 7.0 | + | + | m |
| 5.6 | m | + | + |

Former Travis matrix:

| PHP \ librabbitmq | master | v0.8.0 | v0.7.1 |
| - | - | - | - |
| 8.0 | + | -  | - |
| 7.4 | + | + | + |
| 7.3 | + | + | + |
| 7.2 | m | - | - |
| 7.1 | m | - | - |
| 7.0 | - | m | m |
| 5.6 | m | m | m |

At the same time I've marked all `-m` builds as experimental (allowed to fail), because it seems that not all of them pass the memory test at the moment, because we have memory leaks in PHP 7.3+ builds.

See build here: https://github.com/javer/php-amqp/actions/runs/644118372

**Comment by lstrojny** [comment]
I would even go one step further and have both memory and no memory build for the affected versions:

| PHP \ librabbitmq | master | v0.8.0 | v0.7.1 |
| - | - | - | - |
| 8.0 | + m | + | + |
| 7.4 | + | + m | + |
| 7.3 | + | + | + m |
| 7.2 | + m | + | + |
| 7.1 | + | + m | + |
| 7.0 | + | + | + m |
| 5.6 | + m | + | + |

**Comment by javer** [comment]
@lstrojny Done, here is the build: https://github.com/javer/php-amqp/actions/runs/644413220

**Comment by lstrojny** [comment]
Thank you!

**Pull request merged**
